package edu.xd.bdilab.iotplatform.dao;

import java.util.Date;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.fk_product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String fkProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.getway_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String getwayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_id
     *
     * @return the value of device_info.device_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_id
     *
     * @param deviceId the value for device_info.device_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.fk_product_id
     *
     * @return the value of device_info.fk_product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getFkProductId() {
        return fkProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.fk_product_id
     *
     * @param fkProductId the value for device_info.fk_product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setFkProductId(String fkProductId) {
        this.fkProductId = fkProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_name
     *
     * @return the value of device_info.device_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_name
     *
     * @param deviceName the value for device_info.device_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.create_time
     *
     * @return the value of device_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.create_time
     *
     * @param createTime the value for device_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.getway_id
     *
     * @return the value of device_info.getway_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getGetwayId() {
        return getwayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.getway_id
     *
     * @param getwayId the value for device_info.getway_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setGetwayId(String getwayId) {
        this.getwayId = getwayId;
    }
}