package edu.xd.bdilab.iotplatform.dao;

import java.util.Date;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Integer fkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_type
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_manufacturer
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String productManufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_desc
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_classification
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Byte productClassification;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.fk_user_id
     *
     * @return the value of product_info.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.fk_user_id
     *
     * @param fkUserId the value for product_info.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_type
     *
     * @return the value of product_info.product_type
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_type
     *
     * @param productType the value for product_info.product_type
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_manufacturer
     *
     * @return the value of product_info.product_manufacturer
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getProductManufacturer() {
        return productManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_manufacturer
     *
     * @param productManufacturer the value for product_info.product_manufacturer
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductManufacturer(String productManufacturer) {
        this.productManufacturer = productManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_desc
     *
     * @return the value of product_info.product_desc
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_desc
     *
     * @param productDesc the value for product_info.product_desc
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_classification
     *
     * @return the value of product_info.product_classification
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Byte getProductClassification() {
        return productClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_classification
     *
     * @param productClassification the value for product_info.product_classification
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setProductClassification(Byte productClassification) {
        this.productClassification = productClassification;
    }
}