package edu.xd.bdilab.iotplatform.dao;

public class UserRoleRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.relation_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Integer relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Integer fkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.fk_role_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    private Integer fkRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.relation_id
     *
     * @return the value of user_role_relation.relation_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.relation_id
     *
     * @param relationId the value for user_role_relation.relation_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.fk_user_id
     *
     * @return the value of user_role_relation.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.fk_user_id
     *
     * @param fkUserId the value for user_role_relation.fk_user_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.fk_role_id
     *
     * @return the value of user_role_relation.fk_role_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public Integer getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.fk_role_id
     *
     * @param fkRoleId the value for user_role_relation.fk_role_id
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    public void setFkRoleId(Integer fkRoleId) {
        this.fkRoleId = fkRoleId;
    }
}