package edu.xd.bdilab.iotplatform.mapper;

import edu.xd.bdilab.iotplatform.dao.DeviceInfo;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    int deleteByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    DeviceInfo selectByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 04 20:19:41 CST 2019
     */
    int updateByPrimaryKey(DeviceInfo record);
}